# Generated by Django 4.2.20 on 2025-03-17 00:03

from django.db import migrations, models
import socialmedia.storage


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=socialmedia.storage.S3MediaStorage(), upload_to='item_images/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, storage=socialmedia.storage.S3MediaStorage(), upload_to='profile_pics/'),
        ),
    ]
