# Generated by Django 4.2.20 on 2025-03-17 02:24

from django.db import migrations, models
import socialmedia.models.items
import socialmedia.models.users
import socialmedia.storage


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0002_alter_item_image_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=socialmedia.storage.S3MediaStorage(), upload_to=socialmedia.models.items.item_image_upload_path),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, storage=socialmedia.storage.S3MediaStorage(), upload_to=socialmedia.models.users.item_image_upload_path),
        ),
    ]
