# Generated by Django 4.2.20 on 2025-03-17 03:56

from django.db import migrations, models
import socialmedia.models.posts
import socialmedia.storage


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0003_alter_item_image_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=socialmedia.storage.S3MediaStorage(), upload_to=socialmedia.models.posts.post_image_upload_path),
        ),
    ]
