# Generated by Django 4.2.20 on 2025-04-18 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0004_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='original_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
